package com.cloudsoft.monterey.hello.impl;

import java.io.Serializable;

/**
 * Generated by Cloudsoft Monterey.
 */
public class HelloImpl implements com.cloudsoft.monterey.hello.Hello, Serializable {
	@Override
	public String sayHello(String name) {
	    return("Hello "+name);
	}
}
