package helloclassic;

import java.io.Serializable;

import com.cloudsoftcorp.monterey.network.api.MediationSegmentService;
import com.cloudsoftcorp.monterey.network.api.MediationSegmentServiceFactory;
import com.cloudsoftcorp.monterey.network.api.SegmentServiceContext;
import com.cloudsoftcorp.monterey.network.api.SegmentStateBackup;
import com.cloudsoftcorp.monterey.network.api.SenderReference;

/**
 * Generated by Cloudsoft Monterey.
 */
public class HelloCloudSegmentService implements MediationSegmentService {
	
	public static class Factory implements MediationSegmentServiceFactory {
		public MediationSegmentService newSegmentService(String segment) {
			return new HelloCloudSegmentService();
		}
		public SegmentStateBackup newSegmentBackup(String segment) {
			return null; // Unsupported
		}
	}

	
	private SegmentServiceContext context;
	public void initialize(SegmentServiceContext context, Object stateToResume) {
	    this.context = context;
	}
	
	public void doMediation(SenderReference senderRef, Object data) {
	    context.send(senderRef, "Hello from " + data);
	    context.broadcast("Prompted by " + data);
	}

	public Serializable shutdown() {
		return null;
	}

}
