package com.cloudsoft.monterey.hello;

/**
 * Generated by Cloudsoft Monterey.
 */
public interface ServiceLocator {

	/**
	 * @returns a non-thread-safe service; 
	 * getService should be called once by each and every thread that wishes to use it
	 */
    public com.cloudsoft.monterey.hello.Hello getService(String name);

}
