package com.cloudsoft.monterey.hello;

import com.cloudsoftcorp.monterey.servicebean.access.api.MontereyNetworkEndpoint;

/**
 * Generated by Cloudsoft Monterey.
 */
public class ServiceLocatorImpl implements com.cloudsoft.monterey.hello.ServiceLocator {

    private final MontereyNetworkEndpoint networkEndpoint;
    private final Class<com.cloudsoft.monterey.hello.Hello> clazz = com.cloudsoft.monterey.hello.Hello.class;
    private long serviceCallsTimeoutInMillis = 20 * 1000L;
    
    public ServiceLocatorImpl(MontereyNetworkEndpoint networkEndpoint) {
        if (networkEndpoint == null) {
            throw new NullPointerException("Network-endpoint must not be null");
        }
        this.networkEndpoint = networkEndpoint;
    }
    
    public void setServiceCallsTimeoutInMillis(long serviceCallsTimeoutInMillis) {
        this.serviceCallsTimeoutInMillis = serviceCallsTimeoutInMillis;
    }
    
    public com.cloudsoft.monterey.hello.Hello getService(String name) {
        return networkEndpoint.getService(clazz, name, serviceCallsTimeoutInMillis);
    }
}
